exclude: ['CNAME', 'Gemfile.lock', 'Gemfile', 'Guardfile', 'README.md']

timezone: Europe/Helsinki

permalink: /blog/:categories/:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
      author: "joni"
      comments: true

plugins:
  - jekyll-feed
